use mongodb::{ Collection, IndexModel, bson, error::WriteFailure, options::IndexOptions };
use redis::{ AsyncCommands, RedisError, aio::MultiplexedConnection };
use serde::{ Deserialize, Serialize };
use thiserror::Error;

use crate::{ env::REFRESH_MAX_AGE, utils::jwt::KeyClaims };

#[derive(Deserialize, Serialize)]
pub struct AuthDocument {
    /// Unique ID to the account.
    pub account_id: String,

    /// The token's identifier.
    pub identifier: String,

    /// TTL: REFRESH_MAX_AGE
    pub created_at: bson::DateTime,
}

#[derive(Error, Debug)]
pub enum AuthOperationError {
    #[error("Bad database")] Database(#[from] mongodb::error::Error),
    #[error("Bad bson")] Bson(#[from] mongodb::bson::error::Error),
    #[error("Bad cache")] Cache(#[from] RedisError),
}

#[derive(Clone)]
pub struct AuthOperations {
    collection: Collection<AuthDocument>,
    cache: MultiplexedConnection,
}
impl AuthOperations {
    pub async fn new(
        collection: Collection<AuthDocument>,
        cache: MultiplexedConnection
    ) -> Result<Self, AuthOperationError> {
        collection.create_index(
            IndexModel::builder()
                .keys(bson::doc! { "account_id": 1, "identifier": 1 })
                .options(IndexOptions::builder().unique(true).build())
                .build()
        ).await?;

        collection.create_index(
            IndexModel::builder()
                .keys(bson::doc! { "created_at": 1 })
                .options(IndexOptions::builder().expire_after(*REFRESH_MAX_AGE).build())
                .build()
        ).await?;

        Ok(AuthOperations { collection, cache })
    }

    /// Add token to cache and database.
    pub async fn issue(
        &mut self,
        claims: KeyClaims,
        created_at: u64
    ) -> Result<bool, AuthOperationError> {
        let cache_key = format!("account:{}:token:{}", &claims.account_id, &claims.identifier);

        // Add database entry as a fallback.
        let result = self.collection.insert_one(AuthDocument {
            account_id: claims.account_id,
            identifier: claims.identifier,
            created_at: bson::DateTime::from_millis((created_at * 1000) as i64),
        }).await;

        match result {
            Ok(_) => {}
            Err(error) => {
                match *error.kind {
                    mongodb::error::ErrorKind::Write(WriteFailure::WriteError(ref write_error)) if
                        write_error.code == 11000
                    => {
                        return Ok(false);
                    }
                    _ => {
                        return Err(AuthOperationError::Database(error));
                    }
                }
            }
        }

        // Preload cache.
        redis
            ::cmd("SET")
            .arg(&cache_key)
            .arg(true)
            .arg("EX")
            .arg(REFRESH_MAX_AGE.as_secs())
            .exec_async(&mut self.cache).await?;

        Ok(true)
    }

    /// This method assumes that the `KeyClaims` provided is generated by server or verified by `jsonwebtoken`.
    ///
    /// Works with token and refresh. The document is set TTL to `REFRESH_MAX_AGE`, but the token has a shorter life span
    /// of `TOKEN_MAX_AGE`.When `jsonwebtoken` invalidates the token, the expired token won't reach here.
    ///
    /// But in some cases, better be safe than sorry, this method performs a basic manual check against the `exp` field of the key.
    pub async fn check_token(&mut self, claims: &KeyClaims) -> Result<bool, AuthOperationError> {
        let current_time = jsonwebtoken::get_current_timestamp();

        let status = self.cache.get::<String, Option<bool>>(
            format!("account:{}:token:{}", claims.account_id, claims.identifier)
        ).await?;

        return match status {
            Some(true) => Ok(current_time <= claims.exp),
            Some(false) => Ok(false),
            None => self.refetch(claims, current_time).await,
        };
    }

    pub async fn revoke(&mut self, claims: &KeyClaims) -> Result<bool, AuthOperationError> {
        self.cache.set::<String, bool, String>(
            format!("account:{}:token:{}", &claims.account_id, &claims.identifier),
            false
        ).await?;

        let db_result = self.collection.delete_one(
            bson::doc! { "account_id": &claims.account_id, "identifier": &claims.identifier }
        ).await?;

        Ok(db_result.deleted_count == 1)
    }

    pub async fn revoke_all(&mut self, account_id: &str) -> Result<u64, AuthOperationError> {
        let mut tokens_cursor = self.collection.find(
            bson::doc! { "account_id": account_id }
        ).await?;

        // Loop through database to batch a cache request for all tokens.
        let mut mset_props: Vec<(String, bool)> = Vec::new();
        while tokens_cursor.advance().await? {
            let token_doc: AuthDocument = bson::deserialize_from_slice(
                tokens_cursor.current().as_bytes()
            )?;

            mset_props.push((
                format!("account:{}:token:{}", &token_doc.account_id, &token_doc.identifier),
                false,
            ));
        }

        let db_result = self.collection.delete_many(bson::doc! { "account_id": account_id }).await?;

        self.cache.mset::<_, _, String>(&mset_props).await?;

        Ok(db_result.deleted_count)
    }

    /// Cache miss, ask the database instead if this token is valid or not.
    async fn refetch(
        &mut self,
        claims: &KeyClaims,
        current_time: u64
    ) -> Result<bool, AuthOperationError> {
        tracing::info!("Cache miss on account: {}", &claims.account_id);
        let document = self.collection.find_one(
            bson::doc! { "account_id": &claims.account_id, "identifier": &claims.identifier }
        ).await?;

        let cache_key = format!("account:{}:token:{}", claims.account_id, claims.identifier);

        redis
            ::cmd("SET")
            .arg(&cache_key)
            .arg(document.is_some() && current_time <= claims.exp)
            .arg("EX")
            .arg(REFRESH_MAX_AGE.as_secs())
            .exec_async(&mut self.cache).await?;

        Ok(document.is_some() && current_time <= claims.exp)
    }
}
